### ISSUE TITLE
Toast margin on small screen 

### ISSUE THREAD

**Issue by BayuDC** [gifaldyazkaa/chocolattech#24]
![image](https://user-images.githubusercontent.com/62124037/215642201-a07cb7f8-40c1-4488-9bb9-9d68ab0a3c29.png)
The margin left is not working, and how about move the toast to bottom on mobile screen?

**Comment by gifaldyazkaa** [comment]
aight, boleh.
but #23 will be merged soon  (estimated 3~5 days forward).

current codebase in master branch will be overwritten with this pr. because of framework switching.

and this component will no longer be in the new pr. I think doing this would be a waste of effort.

but well, I will try to working on this. because pr is still unpredictable when it will be merged.

**Comment by gifaldyazkaa** [comment]
I think I won't do this thing due to conflicting issue between `master` and `v1.0.0-beta`.
This issue will be marked with _wont fix_ tag.

**Comment by gifaldyazkaa** [comment]
case closed due to `wontfix` & inactivity
